from __future__ import annotations

import gymnasium as gym
import numpy as np

from isaaclab_assets.robots.unitree import UNITREE_GO2_CFG

from isaaclab.assets import ArticulationCfg
from isaaclab.envs import DirectRLEnvCfg
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sim import SimulationCfg, PhysxCfg
from isaaclab.utils import configclass


@configclass
class QuadrupedPathTrackingEnvCfg(DirectRLEnvCfg):
    # env

    num_envs = 1024
    decimation = 4
    episode_length_s = 40.0

    # state_dim = 36: xy_rel(2) + yaw(1) + proj_gravity_b(3) + joint_pos_rel(12)
    #                 + base_lin_vel_b(3) + base_ang_vel_b(3) + joint_vel(12)
    # ("Option A": world SE(2) pose (xy, yaw) + body-frame twist — the minimal
    # Markov floating-base state that also tracks the world path; xy/yaw are
    # cyclic w.r.t. the dynamics, which is why base_lin/ang_vel_b — NOT
    # xy/yaw — appear in f(x)/B(x). yaw is stored as a RAW angle at
    # angle_idx=[2]; every network embeds it as (cos, sin) — see
    # agents/skrl/angle_utils.py — while the env/reward/dynamics stay raw.)
    # obs: x_current(36) + x_ref(36) + u_ref(12) = 84
    action_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(12,), dtype=np.float32)
    observation_space = 84
    state_space = 0

    sim: SimulationCfg = SimulationCfg(dt=1 / 200, render_interval=decimation, physx=PhysxCfg(enable_external_forces_every_iteration=True, min_velocity_iteration_count=1))
    robot_cfg: ArticulationCfg = UNITREE_GO2_CFG.replace(prim_path="/World/envs/env_.*/Robot")
    scene: InteractiveSceneCfg = InteractiveSceneCfg(num_envs=num_envs, env_spacing=2.5, replicate_physics=True)

    action_scale = 0.25

    # path to reference trajectory file (generated by scripts/generate_ref_traj.py)
    traj_path: str = "logs/quadruped/dynamics_data.npz"

    # terminate_on_fall: OFF by default so episodes always run the full length.
    # The reward is pure tracking error (no alive bonus), so never terminating
    # doesn't meaningfully advantage policy optimization, and it makes the
    # Stability-tab metrics (AUC + paper C/lambda envelope fit) well-defined over
    # fixed-length curves during training — the same regime the evaluator uses.
    terminate_on_fall: bool = False
    base_height_min = 0.20  # [m] — terminate if robot falls

    # uniform joint-position noise added to x_ref[0] at reset [rad]
    init_noise_scale: float = 0.05
    # uniform xy/yaw noise added to x_ref[0]'s base pose at reset — gives the
    # controller a nonzero e(0) in those dims too, same role as init_noise_scale
    init_xy_noise_scale: float = 0.1     # [m]
    init_yaw_noise_scale: float = 0.1    # [rad]
