from __future__ import annotations

import gymnasium as gym
import numpy as np

from isaaclab_assets.robots.unitree import UNITREE_GO2_CFG

from isaaclab.assets import ArticulationCfg
from isaaclab.envs import DirectRLEnvCfg
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sim import SimulationCfg
from isaaclab.utils import configclass


@configclass
class QuadrupedPathTrackingEnvCfg(DirectRLEnvCfg):
    # env
    decimation = 4
    episode_length_s = 10.0

    # state_dim = 33, action_dim = 12  (same as vel-tracking)
    # obs: x_current(33) + x_ref(33) + u_ref(12) = 78
    action_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(12,), dtype=np.float32)
    observation_space = 78
    state_space = 0

    sim: SimulationCfg = SimulationCfg(dt=1 / 200, render_interval=decimation)
    robot_cfg: ArticulationCfg = UNITREE_GO2_CFG.replace(prim_path="/World/envs/env_.*/Robot")
    scene: InteractiveSceneCfg = InteractiveSceneCfg(num_envs=4096, env_spacing=2.5, replicate_physics=True)

    action_scale = 0.25

    # path to reference trajectory file (generated by scripts/generate_ref_traj.py)
    traj_path: str = "logs/ref_trajs/quadruped.npz"

    base_height_min = 0.20  # [m] — terminate if robot falls
