label: c2rl (rl=ppo, cm=ccm)
algorithm: c2rl-ppo
num_envs: 1024
method: grid
metric:
  name: Stability/auc_mean
  goal: minimize
parameters:
  agent.discount_factor:
    values:
    - 0.1
    - 0.5
    - 0.9
    - 0.99
  agent.rollouts:
    value: 4
  agent.gae_lambda:
    value: 0.99
  agent.ratio_clip:
    value: 0.3
  agent.std_dev_annealing_kwargs.schedule:
    value: exponential
  cm.cmg_method:
    value: ccm
  agent.learning_rate:
    distribution: log_uniform_values
    min: 1.0e-06
    max: 0.001
  agent.kl_threshold:
    values:
    - 0.004
    - 0.008
    - 0.016
    - 0.032
    - 0.064
  agent.std_dev_annealing:
    values:
    - true
    - false
