"""Trajectory buffer for path-tracking environments.

Stores reference (state, action) sequences generated by a trained
velocity-tracking policy. Each path-tracking env samples a trajectory at
reset and reads (x_ref, u_ref) at every step from it.

File format (unified dynamics data, produced by train.py after vel-tracking):
    x:       float32 (N_trajs, T, state_dim)  — physical robot state
    u:       float32 (N_trajs, T, action_dim) — executed (clipped) actions
    x_dot:   float32 (N_trajs, T, state_dim)  — finite-difference derivatives
    lengths: int64   (N_trajs,)               — valid steps per trajectory
                     (steps >= lengths[n] are the last valid state repeated)

The legacy two-file format (states/actions keys from ref_trajs.npz) is still
accepted for backward compatibility.
"""
from __future__ import annotations

import os

import numpy as np
import torch


class TrajectoryBuffer:
    def __init__(self, traj_path: str, device: str):
        if not os.path.exists(traj_path):
            raise FileNotFoundError(
                f"Locomotion policy (reference trajectory) not found at: {traj_path}. "
                "Please generate it first."
            )
        data = np.load(traj_path)
        states_key = "x" if "x" in data else "states"
        actions_key = "u" if "u" in data else "actions"
        self._states = torch.tensor(data[states_key], dtype=torch.float32, device=device)
        self._actions = torch.tensor(data[actions_key], dtype=torch.float32, device=device)
        self.num_trajs, self.traj_len = self._states.shape[:2]
        # Per-trajectory valid lengths. Padding repeats the last valid state,
        # so clamping the step index to lengths-1 freezes the reference at the
        # final valid (x, u) instead of walking into padded territory.
        if "lengths" in data:
            self._lengths = torch.tensor(data["lengths"], dtype=torch.long, device=device)
        else:
            self._lengths = torch.full((self.num_trajs,), self.traj_len, dtype=torch.long, device=device)
        self.state_dim = self._states.shape[2]
        self.action_dim = self._actions.shape[2]
        self.device = device

    def sample_traj_ids(self, num_envs: int) -> torch.Tensor:
        return torch.randint(0, self.num_trajs, (num_envs,), device=self.device)

    def full(self, traj_ids: torch.Tensor) -> torch.Tensor:
        """The whole reference trajectory per env: ``(N, traj_len, state_dim)``.

        Plot/metric code needs the complete reference path, not the windowed
        slice ``get_window`` returns — a window is sampled at the ref offset
        and only spans the horizon, so reconstructing "the reference" from it
        yields an offset-dependent subsample of the true path.
        """
        return self._states[traj_ids]

    def get(
        self,
        traj_ids: torch.Tensor,
        step: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Args:
            traj_ids: (N,) int64 — which trajectory for each env
            step:     (N,) int64 — current step within trajectory
        Returns:
            x_ref:  (N, state_dim)
            u_ref:  (N, action_dim)
        """
        t = torch.minimum(step.long(), self._lengths[traj_ids] - 1).clamp(min=0)
        x_ref = self._states[traj_ids, t]
        u_ref = self._actions[traj_ids, t]
        return x_ref, u_ref

    def get_window(
        self,
        traj_ids: torch.Tensor,
        step: torch.Tensor,
        window,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """The reference window at steps ``t + k*offset``, ``k = 0..length-1``.

        The Isaac counterpart of ``BaseEnv.construct_state``'s window lookup —
        same clamping (hold the trajectory's final valid reference rather than
        walking into padded territory), so both env families produce the same
        layout from the same ``RefWindow``.

        Returns ``(x_refs, u_refs)`` shaped ``(N, length, state_dim)`` /
        ``(N, length, action_dim)``.
        """
        k = torch.arange(window.length, device=self.device, dtype=torch.long)
        t = step.long().unsqueeze(-1) + k.unsqueeze(0) * window.offset      # (N, L)
        last = (self._lengths[traj_ids] - 1).unsqueeze(-1)
        t = torch.minimum(t, last).clamp(min=0)
        ids = traj_ids.unsqueeze(-1).expand_as(t)
        return self._states[ids, t], self._actions[ids, t]

    def initial_state(self, traj_ids: torch.Tensor) -> torch.Tensor:
        """Returns x_ref at step 0 for use during reset."""
        t = torch.zeros(len(traj_ids), dtype=torch.long, device=self.device)
        return self._states[traj_ids, t]
