"""Trajectory buffer for path-tracking environments.

Stores reference (state, action) sequences generated by a trained
velocity-tracking policy. Each path-tracking env samples a trajectory at
reset and reads (x_ref, u_ref) at every step from it.

File format (produced by scripts/generate_ref_traj.py):
    states:  float32 (N_trajs, T, state_dim)  — physical robot state
    actions: float32 (N_trajs, T, action_dim) — reference joint targets
"""
from __future__ import annotations

import os

import numpy as np
import torch


class TrajectoryBuffer:
    def __init__(self, traj_path: str, device: str):
        if not os.path.exists(traj_path):
            raise FileNotFoundError(
                f"Locomotion policy (reference trajectory) not found at: {traj_path}. "
                "Please generate it first."
            )
        data = np.load(traj_path)
        self._states = torch.tensor(data["states"], dtype=torch.float32, device=device)
        self._actions = torch.tensor(data["actions"], dtype=torch.float32, device=device)
        self.num_trajs, self.traj_len = self._states.shape[:2]
        self.state_dim = self._states.shape[2]
        self.action_dim = self._actions.shape[2]
        self.device = device

    def sample_traj_ids(self, num_envs: int) -> torch.Tensor:
        return torch.randint(0, self.num_trajs, (num_envs,), device=self.device)

    def get(
        self,
        traj_ids: torch.Tensor,
        step: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Args:
            traj_ids: (N,) int64 — which trajectory for each env
            step:     (N,) int64 — current step within trajectory
        Returns:
            x_ref:  (N, state_dim)
            u_ref:  (N, action_dim)
        """
        t = step.clamp(0, self.traj_len - 1).long()
        x_ref = self._states[traj_ids, t]
        u_ref = self._actions[traj_ids, t]
        return x_ref, u_ref

    def initial_state(self, traj_ids: torch.Tensor) -> torch.Tensor:
        """Returns x_ref at step 0 for use during reset."""
        t = torch.zeros(len(traj_ids), dtype=torch.long, device=self.device)
        return self._states[traj_ids, t]
